name = "Eternal"
author = "Rinnray"
version = "2.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12aff023956e6f1dd37207699413a1438d0d0c408bc4948e0584c7c0aeaa7d9f"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
