name = "Eternal"
author = "Rinnray"
version = "4.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d07e8684fb43cc38f3b3172ccdb980ab6f31ebe88de773130fd09244019d7db"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
