name = "Eternal"
author = "Rinnray"
version = "4.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "058f6937240b8b444004d8a832154722c84f4e530d041fc3197c3d3ec232eca7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.103"

[options]
acceptable-game-versions = ["1.20"]
