name = "Eternal"
author = "Rinnray"
version = "4.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8f0d9a0e7c112da3de16a86ca8c63106b90e697bcb2cd2d9ee0e15e8617b7ce"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
