name = "Eternal"
author = "Aethrexal"
version = "6.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2e560c61796128f0df36531e990c167f16c0f898f1364d2eabdec573b1a41b4"

[versions]
minecraft = "1.21"
neoforge = "21.0.147"
