name = "Eternal"
author = "Rinnray"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a144c4774168d93883b23b181d442e38defcf9ec59d0355fcf3ced3e0fba6d0"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.4", "1.16.5"]
