name = "Eternal"
author = "Aethrexal"
version = "6.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6fef5894d34f1918c5c567bc20d509363ea0654212ad002a7b0367c655cdd2de"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.72"

[options]
acceptable-game-versions = ["1.21"]
