name = "Eternal"
author = "Rinnray"
version = "2.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cfdf127675299d8f25e9ba75671da91217ecc2d98f847ad84fce015f5ac5ad8"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
