name = "Eternal"
author = "Aethrexal"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0742b0c51b51fa68731a8967f97eac0c4918a010579d6180aa5e089f7f7a8ae7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
