name = "Eternal"
author = "Rinnray"
version = "1.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86ec65031c13d8fe9504cd8225b6cf3139b87d8dc650a1b09c4e226604a95a61"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.4", "1.16.5"]
