name = "Eternal"
author = "Rinnray"
version = "4.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8621e8b08580434c0f9429066a9421781361f4ea1c05d0693cf77e715e70e435"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
