name = "Eternal"
author = "Rinnray"
version = "2.6.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb3846f26838e197447de3a17c456af07f58bd77159dc11522cee849853c8472"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
