name = "Eternal"
author = "Rinnray"
version = "2.6.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51c426142022974bcff03ecefd03cc99d118a1a7e4d1d1fd1cd0e48ffcceab45"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
