name = "Eternal"
author = "Aethrexal"
version = "7.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b8fa59f3f974482a43514d430ec67133c9e4d8fbbf1c883eb7dd22adbcaa8bb"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
