name = "Eternal"
author = "Aethrexal"
version = "6.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c171a148666191d58ca9157ac1bc95bd5a5f9385e4535a5397ab15f0f808f0d4"

[versions]
minecraft = "1.21"
neoforge = "21.0.147"
