name = "Eternal"
author = "Rinnray"
version = "4.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04deae127a72574d31d0ec6f4b7d073e4222869d8612034ea63ff6faebd44189"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
