name = "Eternal"
author = "Rinnray"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d80175f9bd251a47419a2aae1f8e23f7b6302fac7ae8e9d90fa7650b4e212ad"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
