name = "Eternal"
author = "Rinnray"
version = "4.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d41f7d0583b35f30127f4816878af9cc065b5fc32626de4e87d90083895553f0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
