name = "Eternal"
author = "Aethrexal"
version = "7.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6eedd0a44c07fa0afd749d4b6abaaa4b8882d15a30531d7bb5c4719d4e58958"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
