name = "Eternal"
author = "Rinnray"
version = "2.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5812c62e84841f22b154853ceaf238856c89bcf07a1934eb9720e57d4087045a"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
