name = "Eternal"
author = "Rinnray"
version = "4.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b777c367985f4f05c83d16b1ad7422b4f230e84bfacd04dc9dbfa7c2d4166199"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
