name = "Eternal"
author = "Rinnray"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b93aa7d27796883715bd8d0a17ab00e22c95c7ce6e81170833e2056ea576b80f"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
