name = "Eternal"
author = "Rinnray"
version = "4.5.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "011152eed88c149b50a5bc17e19db55e9a4a30d780a4e72c14dff2dd9d94c426"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
