name = "Eternal"
author = "Rinnray"
version = "4.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f49e0762e08bb78a75863f6c14791bf0078069f8b2310abaa84653f68dd22c5"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
