name = "Eternal"
author = "Rinnray"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0873a3b8568ae25fd4479cb35a9cc8c813df782e760d580c8e1ccc314f3ddbb1"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
