name = "Eternal"
author = "Rinnray"
version = "2.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e2e86b69b1ecf91b7a8aebb1e13232e65f895be5b6e39be78f5514b5d9df45e4"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
