name = "Eternal"
author = "Rinnray"
version = "2.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72675a5a5cc21e7cff923bf3b7b560fd77145544914ab1ebe3f80c7841eaa98e"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
