name = "Eternal"
author = "Aethrexal"
version = "6.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45f38be133297d9ada357791d782bfb2c2adbb0298177fa3add690dc028fc660"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.72"

[options]
acceptable-game-versions = ["1.21"]
