name = "Eternal"
author = "Rinnray"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "67e243b6f1137b18b240d238b2cddd275b44ad9ba004fdffcc8a02eaf69fd7b0"

[versions]
forge = "43.2.8"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
