name = "Eternal"
author = "Rinnray"
version = "2.6.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "10ca2f0ad6c6b2d24cf78d19c9b8f256d354280e96c13627a2ccc8d15119677d"

[versions]
forge = "40.2.0"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
