name = "Eternal"
author = "Rinnray"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0790032db732c2aa8a9c61307d87e3513598b5bb03f9b363850f74a7c4547a68"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
