name = "Eternal"
author = "Rinnray"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5f26c83ab8c60d43f62cfdafaaba0bcc13734dd6caa79dd3a52962b1cfe3878"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
