name = "Eternal"
author = "Rinnray"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b74b40bf36cb87c344eff092588f13abc04e12eb72708c8125e8f38dc64a0c4"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18.1"]
