name = "Eternal"
author = "Rinnray"
version = "3.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3204989d293de7cf901b9c77f1ec52b88c8c9e916e6124893da5b66131565769"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
