name = "Eternal"
author = "Rinnray"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "391b8564c3b412c7151e21b4028b5160216874d3034aeefe1597f083f976f101"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
