name = "Eternal"
author = "Rinnray"
version = "4.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "caaa9f783e8f1d5a41eb1357fdb535813afb1acdb20bc5135bc4aa80b0e6a7fd"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
