name = "Eternal"
author = "Aethrexal"
version = "7.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dc2ff3c509573bc0eb6694c6f3cc13b517a38a55e37c66de3894e0ddfdd889e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
