name = "Eternal"
author = "Aethrexal"
version = "7.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d524829fdc7198a0828251dbacc5e9390036d96bc63f7c9913d0de1d5733c9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
