name = "Eternal"
author = "Rinnray"
version = "0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "162f6e5de54cd4a987983a42095f5f8817956a578a201a19453b923cf4869ac9"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.4", "1.16.5"]
