name = "Eternal"
author = "Aethrexal"
version = "7.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b415b9dd96985603c1b83c2b9ab0312f66d118ee738e1df938c03c0a886694a8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
