name = "Eternal"
author = "Rinnray"
version = "4.7.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79b6d58de3a5ccbd0161e3be547f988531a545d13abf4af34094a80687de639b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
