name = "Eternal"
author = "Rinnray"
version = "2.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f37976fda48fbb623819e76b6cc4baef7729d9d9001a3567b922c2a2c5fe5abe"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
