name = "Eternal"
author = "Aethrexal"
version = "7.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5775b3dfbc14487dc7c9a89bf0ec7f11af5ee239c048074a88e3403474fbd44b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.122"

[options]
acceptable-game-versions = ["1.21"]
