name = "Eternal"
author = "Rinnray"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0238a7a09a2a54c64f0d594a91694002be33d1ed27ab2b7aedd3244b567bd3ed"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.4", "1.16.5"]
