name = "Eternal"
author = "Rinnray"
version = "2.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8cf4ec3d548d9abf6554a15ab6a525b0d371c848bad230e1c75eeec5da584e"

[versions]
forge = "40.1.86"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
