name = "Eternal"
author = "Rinnray"
version = "3.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d469d0782081e82ad04812e4213fa7102d1f3698daed82473b32cbc0e053907"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"

[options]
acceptable-game-versions = ["1.19"]
