name = "Eternal"
author = "Aethrexal"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08cbb5084ff9f8bd349eb65346a559517d58ce38ed2f3fbc2ecba52d00a45b3b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.116"

[options]
acceptable-game-versions = ["1.21"]
