name = "Eternal"
author = "Aethrexal"
version = "6.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb66abf5e21008f702dffdeb47d646a6961776eb6568159ea8092d62d2def4b1"

[versions]
minecraft = "1.21"
neoforge = "21.0.167"
