name = "Eternal"
author = "Rinnray"
version = "4.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed9f2f97ba230c4889d5d203e5b01dc42f96aed4fbb83954333db637783ed8d7"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.81"

[options]
acceptable-game-versions = ["1.20"]
