name = "Eternal"
author = "Rinnray"
version = "2.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a36f3144ccd7a8d1c75d2a052c0c9a397644d31f7da482f3c40c00847018509a"

[versions]
forge = "40.1.79"
minecraft = "1.18.2"

[options]
acceptable-game-versions = []
