name = "Eternal"
author = "Aethrexal"
version = "6.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef603f89e980e3bbfdda75290ced64c7ba2201cf036cd8f622af6d73c560be4f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.6"

[options]
acceptable-game-versions = ["1.21"]
