name = "Eternal"
author = "Rinnray"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14cdd3e85e2b914261556a58c30867c501b2013c2ce35b3ffeb6997595ca22ce"

[versions]
forge = "36.2.35"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16", "1.16.4", "1.16.5"]
